services:
  django:
    container_name: "django"
    hostname: "django"
    image: "ghcr.io/synkolbasyn/qrigami:django"
    ports:
      - "80"
    env_file:
      - "./.env"
    depends_on:
      - "postgresql"
    restart: "always"

  nginx:
    container_name: "nginx"
    hostname: "nginx"
    image: "ghcr.io/synkolbasyn/qrigami:nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "django"
    restart: "always"

  postgresql:
    container_name: "postgresql"
    hostname: "$POSTGRES_HOST"
    image: "postgres:latest"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - "./database/:/var/lib/postgresql/data"
    env_file:
      - "./.env"
    shm_size: "1gb"
    restart: "always"
