"""Generated by Django 5.1.7 on 2025-03-26 20:06."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """0001_initial."""

    initial = True

    dependencies = (
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    )

    operations = (
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(
                        help_text="Unique credentials identifier",
                        verbose_name="credential id",
                    ),
                ),
                (
                    "credential_public_key",
                    models.BinaryField(
                        help_text="Public key that generated by authentication device",
                        verbose_name="credential public key",
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        help_text="Count of signups for more security",
                        verbose_name="sign count",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that ovnership credentials",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    )
