"""Generated by Django 5.1.7 on 2025-03-26 20:13."""

from django.db import migrations


class Migration(migrations.Migration):

    """0002_alter_credentials_options."""

    dependencies = (
        ("web_authn", "0001_initial"),
    )

    operations = (
        migrations.AlterModelOptions(
            name="credentials",
            options={
                "verbose_name": "credentials",
                "verbose_name_plural": "credentials",
            },
        ),
    )
