"""QRigami. QR code generator site.

Copyright (C) 2025  Andrew Kozmin <syn.kolbasyn.06@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""


from django.conf import settings
from django.db.models import (
    CASCADE,
    BinaryField,
    Model,
    OneToOneField,
    PositiveBigIntegerField,
)
from django.utils.translation import gettext_lazy as _


class Credentials(Model):

    """User public key credentials."""

    user = OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=CASCADE,
        help_text=_("User that ovnership credentials"),
    )
    credential_id = BinaryField(
        verbose_name=_("credential id"),
        help_text=_("Unique credentials identifier"),
    )
    credential_public_key = BinaryField(
        verbose_name=_("credential public key"),
        help_text=_("Public key that generated by authentication device"),
    )
    sign_count = PositiveBigIntegerField(
        verbose_name=_("sign count"),
        help_text=_("Count of signups for more security"),
    )

    class Meta:

        """Credentials meta class."""

        verbose_name = _("credentials")
        verbose_name_plural = _("credentials")

    def __str__(self) -> str:
        """Return str repr of class."""
        return self.user
