name: Build

on:
  push:
    branches:
      - main

jobs:
  nginx:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -
        name: Set up buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/synkolbasyn/qrigami:nginx
          labels: |
            org.opencontainers.image.source="https://github.com/SynKolbasyn/QRigami"
            org.opencontainers.image.description="Nginx image"
            org.opencontainers.image.licenses="AGPL-3.0-or-later"

  django:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -
        name: Set up buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/synkolbasyn/qrigami:django
          labels: |
            org.opencontainers.image.source="https://github.com/SynKolbasyn/QRigami"
            org.opencontainers.image.description="Django image"
            org.opencontainers.image.licenses="AGPL-3.0-or-later"
