name: Build

on:
  push:
    branches:
      - main

jobs:
  nginx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -
        name: Set up buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/mondegrin/qrigami_nginx:latest

  django:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -
        name: Set up buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mondegrin/qrigami_django:latest
